version: "3.8"

services:
  frontend:
    build:
      context: ./murmur-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:4000
    volumes:
      - frontend_node_modules:/app/node_modules
      - frontend_build:/app/dist
    depends_on:
      - backend

  backend:
    build:
      context: ./murmur-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/murmur
      - REDIS_URL=redis://redis:6379
      - CREATE_DEFAULT_ACCOUNTS=true
    env_file:
      - ./murmur-server/.env.development
    volumes:
      - backend_data:/app/data
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=murmur
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1
    volumes:
      - redis_data:/data

volumes:
  frontend_node_modules:
  frontend_build:
  backend_data:
  postgres_data:
  redis_data:
