// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MailRepository is an autogenerated mock type for the MailRepository type
type MailRepository struct {
	mock.Mock
}

// SendResetMail provides a mock function with given fields: email, html
func (_m *MailRepository) SendResetMail(email string, html string) error {
	ret := _m.Called(email, html)

	if len(ret) == 0 {
		panic("no return value specified for SendResetMail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, html)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendVerificationMail provides a mock function with given fields: email, html
func (_m *MailRepository) SendVerificationMail(email string, html string) error {
	ret := _m.Called(email, html)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationMail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, html)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailRepository creates a new instance of MailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailRepository {
	mock := &MailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
